Milestone-02: Mobile-version .
jenadiusnicholaus/my_portifolio_site pull request #4
Opened 2022-02-12 12:47 UTC by jenadiusnicholaus

In this version added .
     > Recent and list of  works done design
     > About me design.

2022-02-12 15:48 UTC, prolajumokeoni requested changes
Hi @jenadiusnicholaus , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there 💯 

## Highlights 
- Good PR 👍🏿 
- Linters are passing 👍🏿 
- Good Readme 👍🏿 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
![almost-there](https://user-images.githubusercontent.com/69638013/153717706-24c516e0-a1c1-4a63-8ed9-4979f5e15439.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +        </section>
- [ ] Kindly use  `display:grid` for the main container of the projects, it is required you use grid to display projects in the section
- [ ]

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                </div>
Figma design           |  Your design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/69638013/153716370-3160ebeb-0f0c-4208-90dd-3ca89a67b4fa.png) |  ![hisworks](https://user-images.githubusercontent.com/69638013/153716423-52ff2822-03d5-4252-af9d-747d6fdf07bb.PNG)

- [ ] Kindly use the appropriate font colors, and sizes for these content check  screenshot above ⬆️ 
- [ ] Kindly add hover effect to button

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                <button class="btn-get-my-resume" type="button">Get my resume</button>
- [ ] Kindly remove border from the button so it looks like the button in the Figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button  type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 15:48 UTC, prolajumokeoni commented on index.html
> +                        <button type="button" class="">See Project </button>
- [ ]  Kindly add hover effect to button so it looks like button in the figma design

2022-02-12 16:50 UTC, jenadiusnicholaus commented on index.html
> +        </section>
But was thinking that  display:grid is need in  during the desktop version of tho f the app. right?

2022-02-12 16:54 UTC, prolajumokeoni commented on index.html
> +        </section>
@jenadiusnicholaus  part of the requirements is to use display :  grid for the main container wrapping all the projects

2022-02-12 16:56 UTC, prolajumokeoni commented on index.html
> +        </section>
Also each project content is to be aligned with flex box, so I strongly advise you use the display grid for the main container

2022-02-17 08:33 UTC, Kalunge approved these changes
Hi @jenadiusnicholaus , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 08:51 UTC, jenadiusnicholaus commented
Thank you for your comment

2022-02-17 08:51 UTC, merged